### ISSUE TITLE
No response from dark mode button

### ISSUE THREAD

**Issue by ws909** [mousetail/openletter#14]
The dark mode button does not work at all. It should be removed, or fixed.

**Comment by PurpleMagick** [comment]
Browser? Any errors in the console?

**Comment by PurpleMagick** [comment]
Actually, I believe my PR #11 would probably fix this. However, for some reason I cannot test this properly on my machine.

**Comment by ws909** [comment]
> Browser? Any errors in the console?

Safari on iOS and MacOS.
Firefox on Windows 10.

No output in the console in Firefox, when clicking the button, however, two warnings are printed (in Norwegian), on page load:

> Denne siden bruker den ikke-standardiserte egenskapen «zoom». Vurder å bruke calc() i de aktuelle egenskapsverdiene, eller bruk «transform» sammen med «transform-origin: 0 0». [openletter.mousetail.nl](https://openletter.mousetail.nl/)
Infokapsel «» ble avvist som tredjepart.

I did not check the console in Safari.

**Comment by ws909** [comment]
Resolved by PR #11
