### ISSUE TITLE
Automatically recognize light/dark theme, and apply accordingly

### ISSUE THREAD

**Issue by ws909** [mousetail/openletter#15]
Feature request for the website to automatically apply the theme of the browser, until overridden by the setting.

**Comment by PurpleMagick** [comment]
I can do that. I, uh, don't know how to claim an issue. Or whatever. So, posting a message for that.

**Comment by mousetail** [comment]
This might have fixed it, at lest on initial page load: https://github.com/mousetail/openletter/commit/1ed1885a1abb5900eb8ce46118aa0aef70d2cf3f

I'm keeping this issue open if you want to fix the dark mode button on browsers that prefer dark mode
