### ISSUE TITLE
Names don't fit, showing horizontal scrollbar

### ISSUE THREAD

**Issue by marijnschraagen** [mousetail/openletter#24]
The list of signatures is responsive to the browser width and will decrease the number of columns when there is not enough space. However, this doesn't work properly. Long names in the rightmost column are cut off and a scrollbar is visible. See screenshot:

![afbeelding](https://github.com/mousetail/openletter/assets/14089378/a0502e09-fc11-4972-ba7d-e0dd91f20d3e)

It seems to be caused by long names in earlier columns not wrapping:

![afbeelding](https://github.com/mousetail/openletter/assets/14089378/6c7ff55a-d435-4505-a9fa-e5cae8fb0cb1)

Browser: Firefox 113.0.2 on Ubuntu 22.04. Screen resolution: 1920x1080.

Interestingly, this issue only occurs on my laptop (HP Elitebook). On my desktop, same OS and browser version, same resolution, all names are wrapped properly. The issue is persistent through refreshes, the order of the names changes but still long names are not wrapped.

In Chrome it works fine on both computers.

Same issue that is marked as fixed: https://github.com/ArtOfCode-/openletter/issues/2

**Comment by marijnschraagen** [comment]
A hard reload indeed did fix the issue, thanks. Did you change anything in the code, or was it just a matter of me switching it off and on again?

**Comment by mousetail** [comment]
It was fixed a while ago, but CSS can be cached for 30 days

**Comment by mousetail** [comment]
Fixed in #31
