### ISSUE TITLE
How is the signatory list sorted? 

### ISSUE THREAD

**Issue by b-enoit-be** [mousetail/openletter#34]
I see the diamond and ex-diamond going on top of the list, but I cannot understand how the rest is sorted.

It does not seems to be based on the date of signature, nor on the user's display name, nor on their reputation, nor on their user id, ...

Beside the (ex-)diamond being featured, shouldn't the list have a consistent ordering? FWIIW, most of the petitions I see only are sorted by date of signature.

**Comment by mousetail** [comment]
It is sorted randomly

**Comment by tripleee** [comment]
Indeed, https://github.com/mousetail/openletter/blob/8f32b32fdd47375c0cbff34a35ba46c7de57e849/routes/dashboard.ts#L18 sorts first by moderator, then by ex-moderator, then randomly.

(I don't understand why it was designed like this; as the list grows, it would be useful for it to be alphabetized so you can check for a particular user.)

**Comment by ws909** [comment]
> (I don't understand why it was designed like this; as the list grows, it would be useful for it to be alphabetized so you can check for a particular user.)

Ctrl/Cmd + F?

**Comment by tripleee** [comment]
> Ctrl/Cmd + F?

That would be convenient enough if it also worked in various mobile clients.

**Comment by ws909** [comment]
> > Ctrl/Cmd + F?
> 
> That would be convenient enough if it also worked in various mobile clients.

Safari in iOS has it; tap share button, then tap the button which says "search" something. Surely other mobile browsers must have search a basic feature?

**Comment by mousetail** [comment]
You can now sort the list when expanded
